[package]
name = "mk-screens"
version = "0.1.0"
authors = ["Brendan McGloin <stmonkeydoom@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.34"
bitflags = "1.2.1"
derivative = "2.1.1"
dotenv = "0.15.0"
ffmpeg-next = "4.3.7"
ffmpeg-sys-next = "4.3.5"
image = "0.23.12"
libc = "0.2.80"
log = { version = "0.4.11", features = ["release_max_level_debug", "max_level_debug"] }
mime = "0.3.16"
mime_guess = "2.0.3"
pretty_env_logger = "0.4.0"
structopt = "0.3.20"
thiserror = "1.0.22"
