[package]
name = "mk-screens"
version = "0.1.0"
authors = ["Brendan McGloin <stmonkeydoom@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
bitflags = "1"
clap = "2"
config = { version = "0.11", features = ["yaml"], default-features = false }
derivative = "2"
directories = "4"
dotenv = "0.15"
ffmpeg-next = "4"
ffmpeg-sys-next = "4"
filetime = "0.2"
globset = "0.4"
image = "0.23"
indicatif = { version = "0.15", features = ["improved_unicode", "rayon"] }
itertools = "0.9"
lazy_static = "1"
libc = "0.2"
log = { version = "0.4", features = ["release_max_level_debug", "max_level_trace"] }
mime = "0.3"
mime_guess = "2"
pretty_env_logger = "0.4"
rayon = "1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"
thiserror = "1"
