[package]
name = "mk-screens"
version = "0.1.0"
authors = ["Brendan McGloin <stmonkeydoom@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.53"
bitflags = "1.3.2"
clap = "2"
config = { version = "0.11.0", features = ["yaml"], default-features = false }
derivative = "2.2.0"
directories = "4.0.1"
dotenv = "0.15.0"
ffmpeg-next = "4.4.0"
ffmpeg-sys-next = "4.4.0"
filetime = "0.2.15"
globset = "0.4.8"
image = "0.24.0"
indicatif = { version = "0.16.2", features = ["improved_unicode", "rayon"] }
itertools = "0.10.3"
lazy_static = "1.4.0"
libc = "0.2.117"
log = { version = "0.4.14", features = ["release_max_level_debug", "max_level_trace"] }
mime = "0.3.16"
mime_guess = "2.0.3"
pretty_env_logger = "0.4.0"
rayon = "1.5.1"
serde = { version = "1.0.136", features = ["derive"] }
serde_yaml = "0.8.23"
structopt = "0.3.26"
thiserror = "1.0.30"
webp = "0.2.1"
